# Generated by Django 5.2.1 on 2025-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_rename_name_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
