# Generated by Django 5.2.1 on 2025-07-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_alter_service_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceinvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('discount', models.PositiveIntegerField(blank=True)),
                ('tax', models.PositiveBigIntegerField(blank=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.service')),
            ],
        ),
    ]
