# Generated by Django 5.2.1 on 2025-07-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_serviceinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceinvoice',
            old_name='status',
            new_name='paid',
        ),
    ]
