# Generated by Django 5.2.1 on 2025-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0006_rename_status_serviceinvoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinvoice',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='tax',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
