# Generated by Django 5.2.1 on 2025-07-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0007_alter_serviceinvoice_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceinvoice',
            old_name='Service',
            new_name='service',
        ),
    ]
