# Generated by Django 5.0.3 on 2025-08-28 17:18

import customer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0008_rename_service_serviceinvoice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contactNumber',
            field=models.CharField(max_length=10, unique=True, validators=[customer_app.models.validate_phone]),
        ),
    ]
