# Generated by Django 5.2.1 on 2025-06-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='gender',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_app.client'),
            preserve_default=False,
        ),
    ]
