# Generated by Django 5.2.1 on 2025-06-01 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_userdetails_gender_userdetails_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.client'),
        ),
    ]
