# Generated by Django 5.2.1 on 2025-06-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_userdetails_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='subscriptionPlan',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscriptionName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscriptionValidity',
            field=models.CharField(choices=[('Month', 'one month'), ('Aix month', 'six month'), ('One Year', 'one year')], default='M', max_length=30),
        ),
    ]
