# Generated by Django 5.2.1 on 2025-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_subscriptionplan_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.CharField(choices=[('one month', '5000'), ('six month', '25000'), ('one year', '50000')], default='one month', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionName',
            field=models.CharField(default='Monthly', max_length=50),
        ),
    ]
