# Generated by Django 5.2.1 on 2025-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_subscriptionplan_subscriptionamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionValidity',
            field=models.CharField(choices=[('M', 'One month'), ('H', 'Six month'), ('Y', 'One year')], default='M', max_length=30),
        ),
    ]
