# Generated by Django 5.2.1 on 2025-06-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_subscriptionplan_subscriptionvalidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.CharField(choices=[('one month', '5000'), ('six month', '25000'), ('one year', '50000')], default='one month', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionName',
            field=models.CharField(default='Monthly', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionValidity',
            field=models.CharField(choices=[('M', 'One month'), ('H', 'Six month'), ('Y', 'One year')], default='M', max_length=30, unique=True),
        ),
    ]
