# Generated by Django 5.2.1 on 2025-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_subscriptionplan_subscriptionamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.CharField(choices=[('5000', 'one month'), ('25000', 'six month'), ('50000', 'one year')], default='5000', max_length=20, unique=True),
        ),
    ]
