# Generated by Django 5.2.1 on 2025-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_subscriptionplan_subscriptionamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.CharField(default='5000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionValidity',
            field=models.CharField(default='M', max_length=30, unique=True),
        ),
    ]
