# Generated by Django 5.2.1 on 2025-06-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_subscriptionplan_subscriptionamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientActive',
            new_name='is_active',
        ),
    ]
