# Generated by Django 5.2.1 on 2025-06-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_subscriptionplan_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionStart', models.DateField()),
                ('subscriptionEnd', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.client')),
                ('subscribedPlan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.subscriptionplan')),
            ],
        ),
    ]
