# Generated by Django 5.2.1 on 2025-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
