# Generated by Django 5.2.1 on 2025-06-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_subscriber_created_at_subscriber_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbilling',
            name='subscriptionEnd',
        ),
        migrations.RemoveField(
            model_name='clientbilling',
            name='subscriptionStart',
        ),
        migrations.AlterField(
            model_name='clientbilling',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.subscriber'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.subscriptionplan')),
            ],
        ),
    ]
