# Generated by Django 5.2.1 on 2025-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_remove_clientbilling_subscriptionend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbilling',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
