# Generated by Django 5.2.1 on 2025-06-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_clientbilling_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbilling',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.subscriber', unique=True),
        ),
    ]
