# Generated by Django 5.0.3 on 2025-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_alter_clientbilling_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('expired', 'expired')], default='active', max_length=50),
        ),
    ]
