# Generated by Django 5.0.3 on 2025-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_subscriber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.CharField(default='5000', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionValidity',
            field=models.CharField(default='M', max_length=30),
        ),
    ]
