# Generated by Django 5.0.3 on 2025-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_subscriptionplan_subscriptionamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbilling',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.DecimalField(decimal_places=2, default='5000', max_digits=10),
        ),
    ]
