# Generated by Django 5.0.3 on 2025-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_alter_clientbilling_totalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbilling',
            name='totalAmount',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscriptionAmount',
            field=models.CharField(default='5000', max_length=20),
        ),
    ]
