# Generated by Django 5.0.3 on 2025-06-30 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_clientbilling_totalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribedPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribers', to='admin_app.subscriptionplan'),
        ),
    ]
