# Generated by Django 5.2.1 on 2025-07-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_subscriber_subscribedplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribedPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribedplan', to='admin_app.subscriptionplan'),
        ),
    ]
